kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: fedora-s2i-php-nginx-build
  namespace: fedora-s2i-php-builds
  labels:
    name: fedora-s2i-php-nginx-build
spec:
  output:
    to:
      kind: DockerImage
      name: 'quay.io/cuppett/fedora-s2i-php-nginx:latest'
    pushSecret:
      name: quayio
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      from:
        kind: ImageStreamTag
        namespace: fedora-s2i-php-builds
        name: 'fedora-s2i-php-base:latest'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/cuppett/fedora-s2i-php-nginx'
    contextDir: nginx
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  runPolicy: Serial